### ISSUE TITLE
Auth using OIDC

### ISSUE THREAD

**Issue by joeblew999** [dimonomid/nerdlog#31]
https://github.com/openpubkey/opkssh

Would make it easier for many .

Authelia for example is working on supporting it.

It’s in many ways more secure since you can use passkeys with Authelia .

**Comment by cluster2600** [comment]
I have implemented that In my fork, please check my pull request

**Comment by dimonomid** [comment]
As [mentioned in the review](https://github.com/dimonomid/nerdlog/pull/38#pullrequestreview-2866161347), this PR smells 100% AI-generated: there are a bunch of incoherent changes (the new config option which isn't even used, the method returning an interface{} for no good reason, misplaced and very AI-style docs, the ssh-config changes are still present after agreeing to remove them, etc).

I doubt we can get much out of this PR as it is tbh.
